import React,{useEffect,useMemo,useRef,useState}from'react';
import{Alert,FlatList,KeyboardAvoidingView,Platform,SafeAreaView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{LinearGradient}from'expo-linear-gradient';
import*as Contacts from'expo-contacts';
import{supabase}from'./supabase';

type KnownPerson={userId:string;name:string;image?:string};
type ChatTarget={userId:string;name:string;programId:string|null;programTitle:string;channel:string};
type Room={room_id:string;program_id:string|null;program_title:string;member_ids:string[];last_message:string|null;last_message_at:string|null;unread_count:number};
type Msg={id:string;sender_id:string;body:string;created_at:string};
const normalizePhone=(value='')=>{let p=value.replace(/[^\d+]/g,'');if(p.startsWith('0033'))p='+33'+p.slice(4);if(p.startsWith('0'))p='+33'+p.slice(1);if(!p.startsWith('+')&&p.length===9)p='+33'+p;return p};

export default function ChatScreen({userId,initialTarget,unreadCount,onUnreadChange,onBack,onHome,onContacts}:{userId:string;initialTarget:ChatTarget|null;unreadCount:number;onUnreadChange:(n:number)=>void;onBack:()=>void;onHome:()=>void;onContacts:()=>void}){
 const[rooms,setRooms]=useState<Room[]>([]),[roomId,setRoomId]=useState<string|null>(null),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[inviteOpen,setInviteOpen]=useState(false),[knownPeople,setKnownPeople]=useState<KnownPerson[]>([]);
 const startedRef=useRef(false);const listRef=useRef<FlatList<Msg>>(null);
 const names=useMemo(()=>new Map(knownPeople.map(p=>[p.userId,p.name])),[knownPeople]);
 const active=rooms.find(r=>r.room_id===roomId)||null;
 useEffect(()=>{loadPeople();loadRooms()},[]);
 useEffect(()=>{if(initialTarget&&!startedRef.current){startedRef.current=true;start(initialTarget)}},[initialTarget]);
 useEffect(()=>{if(!roomId)return;openRoom(roomId);const t=setInterval(()=>openRoom(roomId),1200);return()=>clearInterval(t)},[roomId]);
 useEffect(()=>{if(roomId)return;const t=setInterval(loadRooms,2000);return()=>clearInterval(t)},[roomId]);
 async function loadPeople(){const perm=await Contacts.getPermissionsAsync();if(perm.status!=='granted')return;const{data}=await Contacts.getContactsAsync({fields:[Contacts.Fields.PhoneNumbers]});const local=new Map<string,string>();data.forEach(c=>(c.phoneNumbers||[]).forEach(n=>{const p=normalizePhone(n.number||'');if(p)local.set(p,c.name||'Contact')}));const phones=[...local.keys()],rows:any[]=[];for(let i=0;i<phones.length;i+=300){const{data:found}=await supabase.rpc('match_contact_phones',{phone_list:phones.slice(i,i+300)});rows.push(...(found||[]))}setKnownPeople(rows.flatMap((r:any)=>{const phone=normalizePhone(r.phone_e164||''),name=local.get(phone);return name?[{userId:r.user_id,name}]:[]}))}
 async function loadRooms(){const{data}=await supabase.rpc('my_chat_rooms_v2');setRooms(((data||[])as Room[]).map(r=>({...r,unread_count:Number(r.unread_count)||0})));const{data:count}=await supabase.rpc('chat_unread_count');onUnreadChange(Number(count)||0)}
 async function openRoom(id:string){await supabase.rpc('mark_chat_read',{p_room_id:id});const{data}=await supabase.rpc('chat_messages_for',{p_room_id:id});setMessages((data||[])as Msg[]);await loadRooms()}
 async function start(p:ChatTarget){const{data,error}=await supabase.rpc('start_chat_with',{target_user:p.userId,p_program_id:p.programId,p_program_title:p.programTitle});if(error)return Alert.alert('Discussion impossible',error.message);await loadRooms();setRoomId(data as string)}
 async function send(){const body=text.trim();if(!body||!roomId)return;const{error}=await supabase.rpc('send_chat_message',{p_room_id:roomId,p_body:body});if(error)return Alert.alert('Message impossible',error.message);setText('');await openRoom(roomId)}
 async function invite(p:KnownPerson){if(!roomId)return;const{error}=await supabase.rpc('invite_chat_member',{p_room_id:roomId,p_user_id:p.userId});if(error)return Alert.alert('Invitation impossible',error.message);setInviteOpen(false);loadRooms()}
 const label=(ids:string[])=>{const o=ids.filter(id=>id!==userId),v=o.slice(0,2).map(id=>names.get(id)||'Participant');return v.join(', ')+(o.length>2?` +${o.length-2}`:'')||'Discussion'};
 if(!roomId)return<SafeAreaView style={s.screen}><View style={s.head}><TouchableOpacity onPress={onBack} style={s.round}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Text style={s.title}>Discussions</Text><View style={{width:42}}/></View><FlatList data={rooms} keyExtractor={r=>r.room_id} contentContainerStyle={s.list} ListEmptyComponent={<View style={s.empty}><Ionicons name="chatbubbles-outline" size={35} color="#6b2cff"/><Text style={s.emptyTitle}>Aucune discussion active</Text><Text style={s.emptyText}>Depuis l’Accueil, touche un proche Onlive pour démarrer une discussion.</Text></View>} renderItem={({item})=><TouchableOpacity onPress={()=>setRoomId(item.room_id)} style={s.room}><View style={{flex:1}}><Text style={s.program}>{item.program_title}</Text><Text style={s.people}>{label(item.member_ids)}</Text><Text numberOfLines={1} style={s.preview}>{item.last_message||'Nouvelle discussion'}</Text></View>{item.unread_count>0&&<View style={s.roomBadge}><Text style={s.badgeText}>{item.unread_count>99?'99+':item.unread_count}</Text></View>}<Ionicons name="chevron-forward" size={20} color="#aaa"/></TouchableOpacity>}/><BottomNav unreadCount={unreadCount} onHome={onHome} onContacts={onContacts}/></SafeAreaView>;
 return<SafeAreaView style={s.screen}><KeyboardAvoidingView style={s.chatLayout} behavior={Platform.OS==='ios'?'padding':'height'} keyboardVerticalOffset={0}><View style={s.head}><TouchableOpacity onPress={()=>{setRoomId(null);loadRooms()}} style={s.round}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><View style={{flex:1,alignItems:'center'}}><Text style={s.chatTitle}>{active?.program_title||initialTarget?.programTitle||'Discussion Onlive'}</Text><Text style={s.chatSub}>{active?label(active.member_ids):initialTarget?.name||''}</Text></View><TouchableOpacity onPress={()=>setInviteOpen(v=>!v)} style={s.round}><Ionicons name="person-add-outline" size={21}/></TouchableOpacity></View>{inviteOpen&&<View style={s.invite}><FlatList horizontal data={knownPeople.filter(p=>!active?.member_ids.includes(p.userId))} keyExtractor={p=>p.userId} renderItem={({item})=><TouchableOpacity onPress={()=>invite(item)} style={s.person}><Text style={s.personName}>{item.name}</Text></TouchableOpacity>}/></View>}<FlatList ref={listRef} data={messages} keyExtractor={m=>m.id} style={s.messageList} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>listRef.current?.scrollToEnd({animated:true})} renderItem={({item})=>{const mine=item.sender_id===userId;return<View style={[s.wrap,mine&&{alignItems:'flex-end'}]}><Text style={s.sender}>{mine?'Moi':names.get(item.sender_id)||'Participant'}</Text><View style={[s.bubble,mine&&s.mine]}><Text style={[s.body,mine&&{color:'#fff'}]}>{item.body}</Text></View></View>}}/><View style={s.composer}><TextInput value={text} onChangeText={setText} placeholder="Message…" style={s.input} multiline blurOnSubmit={false}/><TouchableOpacity onPress={send}><LinearGradient colors={['#4932ff','#ed00b3']} style={s.send}><Ionicons name="arrow-up" size={20} color="#fff"/></LinearGradient></TouchableOpacity></View></KeyboardAvoidingView></SafeAreaView>
}
function BottomNav({unreadCount,onHome,onContacts}:{unreadCount:number;onHome:()=>void;onContacts:()=>void}){return<View style={s.bottomWrap}><View style={s.bottom}><TouchableOpacity onPress={onHome} style={s.nav}><Ionicons name="home-outline" size={21} color="#6b2cff"/><Text style={s.navText}>Accueil</Text></TouchableOpacity><LinearGradient colors={['#4932ff','#ed00b3']} style={[s.nav,s.navSelected]}><View><Ionicons name="chatbubbles" size={21} color="#fff"/>{unreadCount>0&&<View style={s.navBadge}><Text style={s.navBadgeText}>{unreadCount>99?'99+':unreadCount}</Text></View>}</View><Text style={s.navActive}>Discussions</Text></LinearGradient><TouchableOpacity onPress={onContacts} style={s.nav}><Ionicons name="people-outline" size={22} color="#d700b0"/><Text style={[s.navText,{color:'#d700b0'}]}>Contacts</Text></TouchableOpacity></View></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#f6f6f8'},chatLayout:{flex:1},head:{height:64,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},round:{width:42,height:42,borderRadius:21,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},title:{fontSize:21,fontWeight:'900'},list:{padding:14,paddingBottom:92},empty:{backgroundColor:'#fff',borderRadius:24,padding:28,alignItems:'center',marginTop:20},emptyTitle:{fontSize:18,fontWeight:'900',marginTop:8},emptyText:{color:'#777',textAlign:'center',marginTop:6},room:{backgroundColor:'#fff',borderRadius:20,padding:16,marginBottom:10,flexDirection:'row',alignItems:'center',gap:9},program:{fontWeight:'900',fontSize:16},people:{fontSize:13,color:'#6b2cff',fontWeight:'700',marginTop:3},preview:{fontSize:13,color:'#888',marginTop:5},roomBadge:{minWidth:24,height:24,borderRadius:12,backgroundColor:'#ed00b3',alignItems:'center',justifyContent:'center',paddingHorizontal:6},badgeText:{color:'#fff',fontSize:11,fontWeight:'900'},bottomWrap:{position:'absolute',left:0,right:0,bottom:0,height:78,backgroundColor:'#f6f6f8',alignItems:'center',paddingTop:6},bottom:{width:'92%',height:58,flexDirection:'row',backgroundColor:'#fff',borderRadius:29,padding:4,shadowColor:'#000',shadowOpacity:.12,shadowRadius:10,shadowOffset:{width:0,height:3},elevation:7},nav:{flex:1,alignItems:'center',justifyContent:'center',borderRadius:24},navSelected:{borderRadius:24},navText:{fontSize:10,fontWeight:'800',color:'#6b2cff',marginTop:1},navActive:{fontSize:10,fontWeight:'800',color:'#fff',marginTop:1},navBadge:{position:'absolute',right:-11,top:-7,minWidth:17,height:17,borderRadius:9,backgroundColor:'#ff1744',alignItems:'center',justifyContent:'center',paddingHorizontal:4},navBadgeText:{color:'#fff',fontSize:9,fontWeight:'900'},chatTitle:{fontSize:16,fontWeight:'900'},chatSub:{fontSize:11,color:'#777'},invite:{backgroundColor:'#fff',padding:10},person:{backgroundColor:'#eee',padding:10,borderRadius:14,marginRight:8},personName:{fontWeight:'800'},messageList:{flex:1},messages:{padding:14,paddingBottom:10,flexGrow:1,justifyContent:'flex-end'},wrap:{marginBottom:10,alignItems:'flex-start'},sender:{fontSize:10,color:'#999',marginBottom:3},bubble:{maxWidth:'82%',backgroundColor:'#fff',padding:11,borderRadius:16},mine:{backgroundColor:'#6b2cff'},body:{fontSize:15},composer:{flexDirection:'row',alignItems:'flex-end',gap:8,paddingHorizontal:10,paddingTop:8,paddingBottom:10,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#ededf1'},input:{flex:1,maxHeight:100,minHeight:44,backgroundColor:'#f1f1f4',borderRadius:20,paddingHorizontal:14,paddingVertical:11,fontSize:16,color:'#111'},send:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'}});