import React,{useState}from'react';
import{FlatList,Image,KeyboardAvoidingView,Platform,SafeAreaView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{LinearGradient}from'expo-linear-gradient';

type ChatTarget={userId:string;name:string;programId:string|null;programTitle:string;channel:string};
type ReviewProgram={id:string;title:string;channel:string};
type Props={initialTarget:ChatTarget|null;reviewProgram:ReviewProgram|null;onBack:()=>void;onHome:()=>void;onContacts:()=>void;onProfile:()=>void;profileAvatar:string|null;profileInitials:string};
type DemoMessage={mine:boolean;body:string;time:string};

export default function ReviewChatScreen({initialTarget,reviewProgram,onBack,onHome,onContacts,onProfile,profileAvatar,profileInitials}:Props){
 const[room,setRoom]=useState<string|null>(initialTarget?.userId||null),[text,setText]=useState('');
 const[messages,setMessages]=useState<Record<string,DemoMessage[]>>({
  'review-demo-alexandre':[{mine:false,body:'Alors prêt pour le programme ? 👀',time:'20h50'},{mine:true,body:'Oui ! On regarde ça ensemble 😄',time:'20h52'}],
  'review-demo-thomas':[{mine:false,body:'Tu as vu ce passage ? 😮',time:'21h12'}],
  'review-demo-group':[{mine:false,body:'On est tous là 🔥',time:'21h20'}]
 });
 const rooms=[{id:'review-demo-alexandre',label:'Moi, Alexandre R.',preview:'Oui ! On regarde ça ensemble 😄'},{id:'review-demo-thomas',label:'Moi, Thomas Dupont',preview:'Tu as vu ce passage ? 😮'},{id:'review-demo-group',label:'Moi, Papa, Kevin, Ludo',preview:'On est tous là 🔥'}];
 const send=()=>{const body=text.trim();if(!body||!room)return;const d=new Date(),time=`${String(d.getHours()).padStart(2,'0')}h${String(d.getMinutes()).padStart(2,'0')}`;setMessages(v=>({...v,[room]:[...(v[room]||[]),{mine:true,body,time}]}));setText('')};
 if(!reviewProgram)return<SafeAreaView style={s.screen}><View style={s.head}><TouchableOpacity onPress={onBack} style={s.round}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Text style={s.title}>Discussions</Text><View style={{width:42}}/></View><Text style={s.off}>Sélectionne d’abord un programme depuis l’Accueil.</Text><BottomNav onHome={onHome} onContacts={onContacts} onProfile={onProfile} profileAvatar={profileAvatar} profileInitials={profileInitials}/></SafeAreaView>;
 if(!room)return<SafeAreaView style={s.screen}><View style={s.head}><TouchableOpacity onPress={onBack} style={s.round}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><Text style={s.title}>Discussions</Text><View style={{width:42}}/></View><View style={s.programBlock}><Text numberOfLines={1} style={s.program}>{reviewProgram.title}</Text><Text numberOfLines={1} style={s.channel}>{reviewProgram.channel}</Text></View><FlatList data={rooms} keyExtractor={r=>r.id} contentContainerStyle={s.list} renderItem={({item})=><TouchableOpacity onPress={()=>setRoom(item.id)} style={s.room}><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={s.people}>{item.label}</Text><Text numberOfLines={1} style={s.preview}>{item.preview}</Text></View><Text style={s.roomTime}>21h20</Text><Ionicons name="chevron-forward" size={17} color="#c0c0c5"/></TouchableOpacity>}/><BottomNav onHome={onHome} onContacts={onContacts} onProfile={onProfile} profileAvatar={profileAvatar} profileInitials={profileInitials}/></SafeAreaView>;
 const label=room==='review-demo-alexandre'?'Moi, Alexandre R.':room==='review-demo-thomas'?'Moi, Thomas Dupont':'Moi, Papa, Kevin, Ludo';
 const sender=room==='review-demo-alexandre'?'Alexandre R.':room==='review-demo-thomas'?'Thomas Dupont':'Participant';
 return<SafeAreaView style={s.screen}><KeyboardAvoidingView style={s.chatLayout} behavior={Platform.OS==='ios'?'padding':'height'}><View style={s.head}><TouchableOpacity onPress={()=>setRoom(null)} style={s.round}><Ionicons name="chevron-back" size={23}/></TouchableOpacity><View style={s.chatHead}><Text numberOfLines={1} style={s.chatTitle}>{reviewProgram.title}</Text><Text numberOfLines={1} style={s.chatSub}>{label}</Text></View><View style={{width:42}}/></View><FlatList data={messages[room]||[]} keyExtractor={(_,i)=>String(i)} style={{flex:1}} contentContainerStyle={s.messages} renderItem={({item})=><View style={[s.wrap,item.mine&&{alignItems:'flex-end'}]}><Text style={s.sender}>{item.mine?'Moi':sender}</Text><View style={[s.bubble,item.mine&&s.mine]}><Text style={[s.body,item.mine&&{color:'#fff'}]}>{item.body}</Text><Text style={[s.messageTime,item.mine&&s.messageTimeMine]}>{item.time}</Text></View></View>}/><View style={s.composer}><TextInput value={text} onChangeText={setText} placeholder="Message…" style={s.input} multiline/><TouchableOpacity onPress={send}><LinearGradient colors={['#4932ff','#ed00b3']} style={s.send}><Ionicons name="arrow-up" size={20} color="#fff"/></LinearGradient></TouchableOpacity></View></KeyboardAvoidingView></SafeAreaView>;
}
function BottomNav({onHome,onContacts,onProfile,profileAvatar,profileInitials}:{onHome:()=>void;onContacts:()=>void;onProfile:()=>void;profileAvatar:string|null;profileInitials:string}){return<View style={s.bottomWrap}><View style={s.bottom}><TouchableOpacity onPress={onHome} style={s.nav}><Ionicons name="home-outline" size={21} color="#6b2cff"/><Text style={s.navText}>Accueil</Text></TouchableOpacity><LinearGradient colors={['#4932ff','#ed00b3']} style={[s.nav,s.navSelected]}><Ionicons name="chatbubbles" size={21} color="#fff"/><Text style={s.navActive}>Discussions</Text></LinearGradient><TouchableOpacity onPress={onContacts} style={s.nav}><Ionicons name="people-outline" size={22} color="#d700b0"/><Text style={[s.navText,{color:'#d700b0'}]}>Contacts</Text></TouchableOpacity><TouchableOpacity onPress={onProfile} style={s.nav}>{profileAvatar?<Image source={{uri:profileAvatar}} style={s.avatar}/>:<View style={s.initialCircle}><Text style={s.initial}>{profileInitials}</Text></View>}<Text style={[s.navText,{color:'#555'}]}>Compte</Text></TouchableOpacity></View></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#f6f6f8'},chatLayout:{flex:1},head:{height:64,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},round:{width:42,height:42,borderRadius:21,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},title:{fontSize:21,fontWeight:'900'},off:{fontSize:13,color:'#888',marginHorizontal:18},programBlock:{marginHorizontal:18,marginBottom:8},program:{fontSize:15,color:'#6b2cff',fontWeight:'800'},channel:{fontSize:12,color:'#888',marginTop:2},list:{paddingHorizontal:14,paddingTop:4,paddingBottom:92},room:{backgroundColor:'#fff',borderRadius:16,paddingHorizontal:14,paddingVertical:11,marginBottom:7,flexDirection:'row',alignItems:'center',gap:8},people:{fontSize:15,color:'#111',fontWeight:'600'},preview:{fontSize:13,color:'#888',marginTop:3},roomTime:{fontSize:11,color:'#999'},chatHead:{flex:1,minWidth:0,paddingHorizontal:10},chatTitle:{fontSize:14,fontWeight:'700'},chatSub:{fontSize:11,color:'#777',marginTop:2},messages:{padding:14,paddingBottom:10,flexGrow:1,justifyContent:'flex-end'},wrap:{marginBottom:10,alignItems:'flex-start'},sender:{fontSize:10,color:'#999',marginBottom:3},bubble:{maxWidth:'82%',backgroundColor:'#fff',padding:11,borderRadius:16},mine:{backgroundColor:'#6b2cff'},body:{fontSize:15},messageTime:{fontSize:9,color:'#999',alignSelf:'flex-end',marginTop:4},messageTimeMine:{color:'rgba(255,255,255,.72)'},composer:{flexDirection:'row',alignItems:'flex-end',gap:8,paddingHorizontal:10,paddingTop:8,paddingBottom:10,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#ededf1'},input:{flex:1,maxHeight:100,minHeight:44,backgroundColor:'#f1f1f4',borderRadius:20,paddingHorizontal:14,paddingVertical:11,fontSize:16},send:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},bottomWrap:{position:'absolute',left:0,right:0,bottom:0,height:78,backgroundColor:'#f6f6f8',alignItems:'center',paddingTop:6},bottom:{width:'92%',height:58,flexDirection:'row',backgroundColor:'#fff',borderRadius:29,padding:4},nav:{flex:1,alignItems:'center',justifyContent:'center',borderRadius:24},navSelected:{borderRadius:24},navText:{fontSize:10,fontWeight:'400',color:'#6b2cff',marginTop:1},navActive:{fontSize:10,fontWeight:'400',color:'#fff',marginTop:1},avatar:{width:27,height:27,borderRadius:14},initialCircle:{width:27,height:27,borderRadius:14,backgroundColor:'#eeeef3',alignItems:'center',justifyContent:'center'},initial:{fontSize:10,fontWeight:'900',color:'#444'}});
