import React,{useEffect,useState}from'react';
import{Alert,Image,Linking,Modal,StyleSheet,Text,TextInput,TouchableOpacity,useWindowDimensions,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{Ionicons}from'@expo/vector-icons';
import{LinearGradient}from'expo-linear-gradient';
import MainApp from'./MainApp';
import ChatScreen from'./ChatScreen';
import{supabase}from'./supabase';
import{Notifications,registerPushNotifications,setAppBadge}from'./notifications';

type ChatTarget={userId:string;name:string;programId:string|null;programTitle:string;channel:string};
const ONBOARDING_KEY='@onlive/proches-onboarding';

export default function Root(){
 const{width}=useWindowDimensions();
 const isTablet=width>=768;
 const[mode,setMode]=useState<'app'|'chat'>('app');
 const[appSection,setAppSection]=useState<'home'|'contacts'>('home');
 const[userId,setUserId]=useState<string|null>(null);
 const[reviewMode,setReviewMode]=useState(false);
 const[reviewProgram,setReviewProgram]=useState<{id:string;title:string;channel:string}|null>(null);
 const[chatTarget,setChatTarget]=useState<ChatTarget|null>(null);
 const[notificationRoomId,setNotificationRoomId]=useState<string|null>(null);
 const[unreadCount,setUnreadCount]=useState(0);
 const[forgotOpen,setForgotOpen]=useState(false);
 const[resetOpen,setResetOpen]=useState(false);
 const[accountOpen,setAccountOpen]=useState(false);
 const[onboardingOpen,setOnboardingOpen]=useState(false);
 const[profileOpenSignal,setProfileOpenSignal]=useState(0);
 const[navAvatar,setNavAvatar]=useState<string|null>(null);
 const[navInitials,setNavInitials]=useState('MO');
 const[deleteLoading,setDeleteLoading]=useState(false);
 const[notificationPrefs,setNotificationPrefs]=useState({chat_messages:true,chat_invites:true,favorite_alerts:true});
 const[resetEmail,setResetEmail]=useState('');
 const[newPassword,setNewPassword]=useState('');
 const[confirmPassword,setConfirmPassword]=useState('');
 const[resetLoading,setResetLoading]=useState(false);

 useEffect(()=>{
  supabase.auth.getSession().then(({data})=>{setUserId(data.session?.user.id||null);setReviewMode((data.session?.user.email||'').toLowerCase()==='review@onlive-app.com')});
  const{data:l}=supabase.auth.onAuthStateChange((event,s)=>{setUserId(s?.user.id||null);setReviewMode((s?.user.email||'').toLowerCase()==='review@onlive-app.com');if(event==='PASSWORD_RECOVERY')setResetOpen(true)});
  return()=>l.subscription.unsubscribe();
 },[]);
 useEffect(()=>{
  if(!userId||reviewMode){setOnboardingOpen(false);return}
  let alive=true;
  const key=`${ONBOARDING_KEY}:${userId}`;
  AsyncStorage.getItem(key).then(v=>{if(alive&&!v)setTimeout(()=>alive&&setOnboardingOpen(true),650)}).catch(()=>{});
  return()=>{alive=false};
 },[userId,reviewMode]);
 useEffect(()=>{
  const handleUrl=async(url:string|null)=>{if(!url)return;const isRecovery=url.startsWith('onlive://reset-password');const isConfirmation=url.startsWith('onlive://email-confirmed');if(!isRecovery&&!isConfirmation)return;try{const query=url.includes('?')?url.split('?')[1].split('#')[0]:'';const hash=url.includes('#')?url.split('#')[1]:'';const q=new URLSearchParams(query);const h=new URLSearchParams(hash);const get=(key:string)=>q.get(key)||h.get(key);const errorDescription=get('error_description')||get('error');if(errorDescription)throw new Error(decodeURIComponent(errorDescription));const code=get('code');const accessToken=get('access_token');const refreshToken=get('refresh_token');if(code){const{error}=await supabase.auth.exchangeCodeForSession(code);if(error)throw error}else if(accessToken&&refreshToken){const{error}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(error)throw error}setForgotOpen(false);setNotificationRoomId(null);setChatTarget(null);setAppSection('home');setMode('app');if(isRecovery)setResetOpen(true);else Alert.alert('Adresse confirmée','Ton adresse e-mail est confirmée. Bienvenue sur Onlive !')}catch(e:any){Alert.alert('Lien invalide',e?.message||'Le lien Onlive est invalide ou a expiré.')}};
  Linking.getInitialURL().then(handleUrl);const sub=Linking.addEventListener('url',({url})=>handleUrl(url));return()=>sub.remove();
 },[]);
 useEffect(()=>{if(!userId)return;registerPushNotifications(userId)},[userId]);
 useEffect(()=>{if(!userId)return;supabase.from('notification_preferences').select('chat_messages,chat_invites,favorite_alerts').eq('user_id',userId).maybeSingle().then(({data})=>{if(data)setNotificationPrefs({chat_messages:data.chat_messages!==false,chat_invites:data.chat_invites!==false,favorite_alerts:data.favorite_alerts!==false})})},[userId]);
 useEffect(()=>{if(!userId){setNavAvatar(null);setNavInitials('MO');return;}supabase.from('profiles').select('display_name,avatar_url').eq('id',userId).maybeSingle().then(({data})=>{setNavAvatar(data?.avatar_url||null);const v=(data?.display_name||'Moi').trim().split(/\s+/).filter(Boolean);setNavInitials((v.length>1?`${v[0][0]}${v[v.length-1][0]}`:(v[0]||'MO').slice(0,2)).toUpperCase())})},[userId,profileOpenSignal]);
 useEffect(()=>{if(!userId){setUnreadCount(0);setAppBadge(0);return}let alive=true;const refresh=async()=>{const{data}=await supabase.rpc('chat_unread_count');const n=Number(data)||0;if(alive){setUnreadCount(n);setAppBadge(n)}};refresh();const t=setInterval(refresh,2000);return()=>{alive=false;clearInterval(t)}},[userId]);
 useEffect(()=>{const sub=Notifications.addNotificationResponseReceivedListener(response=>{const d:any=response.notification.request.content.data||{};if((d.type==='chat_message'||d.type==='chat_invite')&&d.roomId){setChatTarget(null);setNotificationRoomId(String(d.roomId));setMode('chat')}else if(d.type==='watching'){setNotificationRoomId(null);setChatTarget(null);setAppSection('home');setMode('app')}});return()=>sub.remove()},[]);

 const sendResetEmail=async()=>{const email=resetEmail.trim().toLowerCase();if(!email)return Alert.alert('Adresse e-mail','Entre l’adresse e-mail de ton compte Onlive.');setResetLoading(true);try{const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'onlive://reset-password'});if(error)throw error;setForgotOpen(false);Alert.alert('E-mail envoyé','Ouvre le mail puis touche le lien : Onlive s’ouvrira directement pour choisir ton nouveau mot de passe.')}catch(e:any){Alert.alert('Envoi impossible',e?.message||'Impossible d’envoyer le mail de réinitialisation.')}finally{setResetLoading(false)}};
 const closeReset=()=>{if(resetLoading)return;setResetOpen(false);setNewPassword('');setConfirmPassword('')};
 const saveNewPassword=async()=>{if(newPassword.length<6)return Alert.alert('Mot de passe trop court','Choisis au moins 6 caractères.');if(newPassword!==confirmPassword)return Alert.alert('Mots de passe différents','Les deux mots de passe doivent être identiques.');setResetLoading(true);try{const{error}=await supabase.auth.updateUser({password:newPassword});if(error)throw error;closeReset();Alert.alert('Mot de passe modifié','Ton nouveau mot de passe est enregistré.')}catch(e:any){Alert.alert('Modification impossible',e?.message||'Impossible de modifier le mot de passe.')}finally{setResetLoading(false)}};
 const performDeleteAccount=async()=>{if(deleteLoading)return;setDeleteLoading(true);try{const{error}=await supabase.functions.invoke('delete-account',{body:{confirm:true}});if(error)throw error;await supabase.auth.signOut({scope:'local'}).catch(()=>{});setAccountOpen(false);setUserId(null);setUnreadCount(0);setChatTarget(null);setNotificationRoomId(null);setAppSection('home');setMode('app');setAppBadge(0);Alert.alert('Compte supprimé','Ton compte Onlive et tes données personnelles ont été supprimés.')}catch(e:any){Alert.alert('Suppression impossible',e?.message||'Impossible de supprimer ton compte pour le moment. Réessaie dans quelques instants.')}finally{setDeleteLoading(false)}};
 const confirmDeleteAccount=()=>Alert.alert('Supprimer mon compte ?','Cette action supprimera définitivement ton profil, ta photo, tes notifications et tes données Onlive. Elle est irréversible.',[{text:'Annuler',style:'cancel'},{text:'Continuer',style:'destructive',onPress:()=>Alert.alert('Dernière confirmation','Veux-tu vraiment supprimer définitivement ton compte Onlive ?',[{text:'Annuler',style:'cancel'},{text:'Supprimer définitivement',style:'destructive',onPress:performDeleteAccount}])}]);
 const performSignOut=async()=>{if(deleteLoading)return;try{await supabase.auth.signOut();}catch{}setAccountOpen(false);setOnboardingOpen(false);setUserId(null);setUnreadCount(0);setChatTarget(null);setNotificationRoomId(null);setAppSection('home');setMode('app');setAppBadge(0)};
 const toggleNotificationPref=async(key:'chat_messages'|'chat_invites'|'favorite_alerts')=>{if(!userId)return;const next={...notificationPrefs,[key]:!notificationPrefs[key]};setNotificationPrefs(next);const{error}=await supabase.from('notification_preferences').upsert({user_id:userId,...next,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error){setNotificationPrefs(notificationPrefs);Alert.alert('Réglage impossible',error.message)}};
 const openDiscussions=()=>{setProfileOpenSignal(0);setMode('chat')};
 const startChat=async(target:ChatTarget)=>{if(reviewMode&&target.userId.startsWith('review-demo-')){setProfileOpenSignal(0);setNotificationRoomId(null);setChatTarget(target);setMode('chat');return}if(!userId||!target.programId)return Alert.alert('Discussion indisponible','Tu dois être Onlive sur le même programme que ton proche pour discuter.');const{data:mine}=await supabase.from('live_status').select('is_live,program_id,started_at').eq('user_id',userId).maybeSingle();const{data:theirs}=await supabase.from('live_status').select('is_live,program_id,started_at').eq('user_id',target.userId).maybeSingle();const fresh=(v:any)=>Boolean(v?.is_live&&v?.program_id&&v?.started_at&&Date.now()-new Date(v.started_at).getTime()<4*60*60*1000);if(!fresh(mine))return Alert.alert('Tu es Offlive','Choisis d’abord le programme que tu regardes pour pouvoir discuter.');if(mine?.program_id!==target.programId)return Alert.alert('Programme différent',`Tu peux voir que ${target.name} est Onlive, mais vous devez regarder le même programme pour discuter.`);if(!fresh(theirs)||theirs?.program_id!==mine?.program_id)return Alert.alert('Programme différent',`${target.name} ne regarde plus le même programme que toi.`);setProfileOpenSignal(0);setNotificationRoomId(null);setChatTarget(target);setMode('chat')};
 const goHome=()=>{setProfileOpenSignal(0);setAppSection('home');setMode('app');if(!isTablet){setChatTarget(null);setNotificationRoomId(null)}};
 const goContacts=()=>{setProfileOpenSignal(0);setAppSection('contacts');setMode('app');if(!isTablet){setChatTarget(null);setNotificationRoomId(null)}};
 const openProfile=()=>{if(!isTablet){setChatTarget(null);setNotificationRoomId(null);setAppSection('home');setMode('app')}setProfileOpenSignal(v=>v+1)};
 const finishOnboarding=async(openContacts=false)=>{if(userId)await AsyncStorage.setItem(`${ONBOARDING_KEY}:${userId}`,'1').catch(()=>{});setOnboardingOpen(false);if(openContacts)goContacts()};

 const mainApp=<MainApp key={userId||'guest'} initialScreen={appSection} onOpenDiscussions={openDiscussions} onStartChat={startChat} onOpenAccount={()=>setAccountOpen(true)} profileOpenSignal={profileOpenSignal} unreadCount={unreadCount} reviewMode={reviewMode} onReviewProgramChange={setReviewProgram}/>;
 const chatKey=notificationRoomId?`room-${notificationRoomId}`:chatTarget?`target-${chatTarget.userId}-${chatTarget.programId||'none'}`:'discussion-list';
 const chat=userId?<ChatScreen key={chatKey} userId={userId} initialTarget={chatTarget} initialRoomId={notificationRoomId} unreadCount={unreadCount} onUnreadChange={setUnreadCount} onBack={()=>{setChatTarget(null);setNotificationRoomId(null);setMode('app')}} onHome={goHome} onContacts={goContacts} onProfile={openProfile} profileAvatar={navAvatar} profileInitials={navInitials} reviewMode={reviewMode} reviewProgram={reviewProgram}/>:null;

 const modals=<>
  <Modal visible={forgotOpen} transparent animationType="fade" onRequestClose={()=>setForgotOpen(false)}><View style={s.modalBackdrop}><View style={s.modalCard}><View style={s.modalHead}><Text style={s.modalTitle}>Mot de passe oublié</Text><TouchableOpacity onPress={()=>setForgotOpen(false)}><Ionicons name="close" size={24}/></TouchableOpacity></View><Text style={s.modalText}>Entre ton e-mail. Onlive t’enverra un lien sécurisé pour choisir ton nouveau mot de passe.</Text><TextInput value={resetEmail} onChangeText={setResetEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Adresse e-mail" style={s.resetInput}/><TouchableOpacity disabled={resetLoading} onPress={sendResetEmail}><LinearGradient colors={['#4932ff','#ed00b3']} style={s.resetButton}><Text style={s.resetButtonText}>{resetLoading?'Envoi…':'Envoyer le lien'}</Text></LinearGradient></TouchableOpacity></View></View></Modal>
  <Modal visible={resetOpen} transparent animationType="fade" onRequestClose={closeReset}><View style={s.modalBackdrop}><View style={s.modalCard}><View style={s.modalHead}><Text style={s.modalTitle}>Nouveau mot de passe</Text><TouchableOpacity accessibilityLabel="Fermer" disabled={resetLoading} onPress={closeReset} style={s.closeBtn}><Ionicons name="close" size={26} color="#111"/></TouchableOpacity></View><Text style={s.modalText}>Choisis ton nouveau mot de passe Onlive.</Text><TextInput value={newPassword} onChangeText={setNewPassword} secureTextEntry placeholder="Nouveau mot de passe" style={s.resetInput}/><TextInput value={confirmPassword} onChangeText={setConfirmPassword} secureTextEntry placeholder="Confirmer le mot de passe" style={s.resetInput}/><TouchableOpacity disabled={resetLoading} onPress={saveNewPassword}><LinearGradient colors={['#4932ff','#ed00b3']} style={s.resetButton}><Text style={s.resetButtonText}>{resetLoading?'Enregistrement…':'Enregistrer'}</Text></LinearGradient></TouchableOpacity></View></View></Modal>
  <Modal visible={accountOpen} transparent animationType="fade" onRequestClose={()=>!deleteLoading&&setAccountOpen(false)}><View style={s.modalBackdrop}><View style={s.modalCard}><View style={s.modalHead}><Text style={s.modalTitle}>Mon compte</Text><TouchableOpacity disabled={deleteLoading} onPress={()=>setAccountOpen(false)} style={s.closeBtn}><Ionicons name="close" size={24} color="#111"/></TouchableOpacity></View><Text style={s.modalText}>Gère ici les informations essentielles liées à ton compte Onlive.</Text><Text style={s.accountSectionTitle}>Notifications</Text><NotificationToggle icon="chatbubble-ellipses-outline" title="Messages" subtitle="Nouveaux messages dans tes discussions" active={notificationPrefs.chat_messages} onPress={()=>toggleNotificationPref('chat_messages')}/><NotificationToggle icon="person-add-outline" title="Invitations" subtitle="Invitations à rejoindre une discussion" active={notificationPrefs.chat_invites} onPress={()=>toggleNotificationPref('chat_invites')}/><NotificationToggle icon="star-outline" title="Favoris" subtitle="Quand un programme correspondant à tes favoris commence" active={notificationPrefs.favorite_alerts} onPress={()=>toggleNotificationPref('favorite_alerts')}/><View style={s.accountDivider}/><TouchableOpacity onPress={()=>Linking.openURL('https://onlive-app.com/privacy')} style={s.accountRow}><View style={s.accountRowIcon}><Ionicons name="shield-checkmark-outline" size={20} color="#6b2cff"/></View><View style={{flex:1}}><Text style={s.accountRowTitle}>Confidentialité</Text><Text style={s.accountRowText}>Consulter la politique de confidentialité</Text></View><Ionicons name="chevron-forward" size={19} color="#999"/></TouchableOpacity><TouchableOpacity onPress={performSignOut} style={s.accountRow}><View style={s.accountRowIcon}><Ionicons name="log-out-outline" size={20} color="#6b2cff"/></View><View style={{flex:1}}><Text style={s.accountRowTitle}>Déconnexion</Text><Text style={s.accountRowText}>Se déconnecter de ce téléphone</Text></View><Ionicons name="chevron-forward" size={19} color="#999"/></TouchableOpacity><View style={s.accountDivider}/><Text style={s.dangerTitle}>Zone sensible</Text><Text style={s.dangerText}>La suppression du compte est définitive. Ton profil, ta photo et tes données personnelles Onlive seront supprimés.</Text><TouchableOpacity disabled={deleteLoading} onPress={confirmDeleteAccount} style={s.deleteButton}><Ionicons name="trash-outline" size={19} color="#d70026"/><Text style={s.deleteButtonText}>{deleteLoading?'Suppression…':'Supprimer mon compte'}</Text></TouchableOpacity></View></View></Modal>
  <Modal visible={onboardingOpen} transparent animationType="slide" onRequestClose={()=>finishOnboarding(false)}><View style={s.onboardingBackdrop}><View style={s.onboardingSheet}><View style={s.onboardingHandle}/><View style={s.onboardingIcon}><Ionicons name="people" size={30} color="#fff"/></View><Text style={s.onboardingTitle}>Onlive, c’est mieux avec tes proches 💜</Text><Text style={s.onboardingText}>Pour voir qui regarde la même chose que toi, tes proches doivent eux aussi avoir Onlive.</Text><Text style={s.onboardingText}>Découvre qui est déjà sur l’app ou invite ceux avec qui tu veux partager tes soirées TV.</Text><TouchableOpacity onPress={()=>finishOnboarding(true)}><LinearGradient colors={['#4932ff','#ed00b3']} style={s.onboardingButton}><Ionicons name="people-outline" size={20} color="#fff"/><Text style={s.onboardingButtonText}>Voir mes proches</Text></LinearGradient></TouchableOpacity><TouchableOpacity onPress={()=>finishOnboarding(false)} style={s.onboardingLater}><Text style={s.onboardingLaterText}>Plus tard</Text></TouchableOpacity></View></View></Modal>
 </>;

 if(isTablet&&userId)return<View style={s.tabletRoot}>
  <View style={s.sideNav}>
   <View style={s.sideTop}>
    <TabletNavItem active={appSection==='home'} icon="home" label="Accueil" onPress={goHome}/>
    <TabletNavItem active={mode==='chat'} icon="chatbubbles" label="Discussions" badge={unreadCount} onPress={openDiscussions}/>
    <TabletNavItem active={appSection==='contacts'} icon="people" label="Contacts" onPress={goContacts}/>
   </View>
   <TouchableOpacity onPress={openProfile} style={s.sideAccount}>{navAvatar?<Image source={{uri:navAvatar}} style={s.sideAvatar}/>:<View style={s.sideInitialCircle}><Text style={s.sideInitialText}>{navInitials}</Text></View>}<Text style={s.sideLabel}>Compte</Text></TouchableOpacity>
  </View>
  <View style={s.tabletMain}><View style={s.tabletMainInner}>{mainApp}</View></View>
  <View style={s.tabletDivider}/>
  <View style={s.tabletChatPane}><View style={s.tabletChatInner}>{chat}</View></View>
  {modals}
 </View>;

 if(mode==='chat'&&userId)return<View style={s.root}>{chat}{modals}</View>;
 return<View style={s.root}>{mainApp}{!userId&&<TouchableOpacity style={s.forgotButton} onPress={()=>setForgotOpen(true)}><Text style={s.forgotText}>Mot de passe oublié ?</Text></TouchableOpacity>}{userId&&<View style={s.navCover}><View style={s.compactNav}><NavItem active={appSection==='home'} icon="home" label="Accueil" onPress={goHome}/><TouchableOpacity onPress={openDiscussions} style={s.navItem}><View style={s.inactive}><View><Ionicons name="chatbubbles-outline" size={21} color="#9728df"/>{unreadCount>0&&<View style={s.badge}><Text style={s.badgeText}>{unreadCount>99?'99+':unreadCount}</Text></View>}</View><Text style={[s.inactiveText,{color:'#9728df'}]}>Discussions</Text></View></TouchableOpacity><NavItem active={appSection==='contacts'} icon="people" label="Contacts" onPress={goContacts}/><TouchableOpacity onPress={openProfile} style={s.navItem}><View style={s.inactive}>{navAvatar?<Image source={{uri:navAvatar}} style={s.navAvatar}/>:<View style={s.navInitialCircle}><Text style={s.navInitialText}>{navInitials}</Text></View>}<Text style={[s.inactiveText,{color:'#555'}]}>Compte</Text></View></TouchableOpacity></View></View>}{modals}</View>;
}

function NotificationToggle({icon,title,subtitle,active,onPress}:{icon:any;title:string;subtitle:string;active:boolean;onPress:()=>void}){return<TouchableOpacity onPress={onPress} style={s.notificationRow}><View style={s.accountRowIcon}><Ionicons name={icon} size={20} color="#6b2cff"/></View><View style={{flex:1}}><Text style={s.accountRowTitle}>{title}</Text><Text style={s.accountRowText}>{subtitle}</Text></View><View style={[s.prefToggle,active&&s.prefToggleActive]}><View style={[s.prefKnob,active&&s.prefKnobActive]}/></View></TouchableOpacity>}

function TabletNavItem({active,icon,label,onPress,badge=0}:{active:boolean;icon:'home'|'chatbubbles'|'people';label:string;onPress:()=>void;badge?:number}){return<TouchableOpacity onPress={onPress} style={s.sideItem}>{active?<LinearGradient colors={['#4932ff','#ed00b3']} style={s.sideActive}><View><Ionicons name={icon} size={25} color="#fff"/>{badge>0&&<View style={s.sideBadge}><Text style={s.sideBadgeText}>{badge>99?'99+':badge}</Text></View>}</View><Text style={s.sideActiveText}>{label}</Text></LinearGradient>:<View style={s.sideInactive}><View><Ionicons name={`${icon}-outline` as any} size={25} color="#7b2cd7"/>{badge>0&&<View style={s.sideBadge}><Text style={s.sideBadgeText}>{badge>99?'99+':badge}</Text></View>}</View><Text style={s.sideInactiveText}>{label}</Text></View>}</TouchableOpacity>}
function NavItem({active,icon,label,onPress}:{active:boolean;icon:'home'|'people';label:string;onPress:()=>void}){return<TouchableOpacity onPress={onPress} style={s.navItem}>{active?<LinearGradient colors={['#4932ff','#ed00b3']} style={s.active}><Ionicons name={icon} size={21} color="#fff"/><Text style={s.activeText}>{label}</Text></LinearGradient>:<View style={s.inactive}><Ionicons name={`${icon}-outline` as any} size={21} color={icon==='people'?'#d700b0':'#6b2cff'}/><Text style={[s.inactiveText,{color:icon==='people'?'#d700b0':'#6b2cff'}]}>{label}</Text></View>}</TouchableOpacity>}

const s=StyleSheet.create({
 root:{flex:1},
 tabletRoot:{flex:1,flexDirection:'row',backgroundColor:'#f6f6f8'},tabletMain:{flex:1.18,minWidth:0,backgroundColor:'#f6f6f8',overflow:'hidden'},tabletMainInner:{position:'absolute',left:0,right:0,top:0,bottom:-78},tabletDivider:{width:1,backgroundColor:'#dedee6'},tabletChatPane:{flex:.90,minWidth:400,backgroundColor:'#f6f6f8',overflow:'hidden'},tabletChatInner:{position:'absolute',left:0,right:0,top:0,bottom:-78},
 sideNav:{width:116,backgroundColor:'#fff',borderRightWidth:1,borderRightColor:'#ececf2',paddingTop:28,paddingBottom:22,justifyContent:'space-between',alignItems:'center'},sideTop:{width:'100%',gap:12},sideItem:{width:'100%',height:76,paddingHorizontal:9},sideActive:{flex:1,borderRadius:19,alignItems:'center',justifyContent:'center'},sideInactive:{flex:1,borderRadius:19,alignItems:'center',justifyContent:'center'},sideActiveText:{fontSize:12,color:'#fff',fontWeight:'700',marginTop:5},sideInactiveText:{fontSize:12,color:'#6d3a93',fontWeight:'600',marginTop:5},sideBadge:{position:'absolute',right:-12,top:-8,minWidth:18,height:18,borderRadius:9,backgroundColor:'#ff1744',alignItems:'center',justifyContent:'center',paddingHorizontal:4},sideBadgeText:{color:'#fff',fontSize:9,fontWeight:'900'},sideAccount:{alignItems:'center',justifyContent:'center',padding:8},sideAvatar:{width:34,height:34,borderRadius:17},sideInitialCircle:{width:34,height:34,borderRadius:17,backgroundColor:'#eeeef3',alignItems:'center',justifyContent:'center'},sideInitialText:{fontSize:11,fontWeight:'900',color:'#444'},sideLabel:{fontSize:11,color:'#555',marginTop:5,fontWeight:'600'},
 navCover:{position:'absolute',left:0,right:0,bottom:0,height:78,backgroundColor:'#f6f6f8',alignItems:'center',justifyContent:'flex-start',paddingTop:6},compactNav:{width:'92%',height:58,backgroundColor:'#fff',borderRadius:29,padding:4,flexDirection:'row',shadowColor:'#000',shadowOpacity:.12,shadowRadius:10,shadowOffset:{width:0,height:3},elevation:7},navItem:{flex:1},active:{flex:1,borderRadius:24,alignItems:'center',justifyContent:'center'},inactive:{flex:1,borderRadius:24,alignItems:'center',justifyContent:'center'},activeText:{fontSize:10,color:'#fff',fontWeight:'400',marginTop:1},inactiveText:{fontSize:10,fontWeight:'400',marginTop:1},badge:{position:'absolute',right:-11,top:-7,minWidth:17,height:17,borderRadius:9,backgroundColor:'#ff1744',alignItems:'center',justifyContent:'center',paddingHorizontal:4},badgeText:{color:'#fff',fontSize:9,fontWeight:'900'},navAvatar:{width:27,height:27,borderRadius:14},navInitialCircle:{width:27,height:27,borderRadius:14,backgroundColor:'#eeeef3',alignItems:'center',justifyContent:'center'},navInitialText:{fontSize:10,fontWeight:'900',color:'#444'},
 forgotButton:{position:'absolute',bottom:26,left:0,right:0,alignItems:'center',paddingVertical:10},forgotText:{color:'#fff',fontWeight:'800',textDecorationLine:'underline'},modalBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,.5)',alignItems:'center',justifyContent:'center',padding:22},modalCard:{width:'100%',maxWidth:430,backgroundColor:'#fff',borderRadius:26,padding:20},modalHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},closeBtn:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center',backgroundColor:'#f1f1f4'},modalTitle:{fontSize:22,fontWeight:'900',color:'#111'},modalText:{fontSize:14,color:'#666',lineHeight:20,marginTop:8,marginBottom:16},resetInput:{height:54,borderWidth:1,borderColor:'#dddde5',borderRadius:15,paddingHorizontal:15,fontSize:16,marginBottom:11},resetButton:{height:54,borderRadius:17,alignItems:'center',justifyContent:'center',marginTop:3},resetButtonText:{color:'#fff',fontSize:16,fontWeight:'900'},accountSectionTitle:{fontSize:16,fontWeight:'900',color:'#111',marginTop:2,marginBottom:5},notificationRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10},prefToggle:{width:44,height:26,borderRadius:13,backgroundColor:'#d8d8df',padding:3,justifyContent:'center'},prefToggleActive:{backgroundColor:'#6b2cff'},prefKnob:{width:20,height:20,borderRadius:10,backgroundColor:'#fff',alignSelf:'flex-start'},prefKnobActive:{alignSelf:'flex-end'},accountRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12},accountRowIcon:{width:38,height:38,borderRadius:19,backgroundColor:'#f2edff',alignItems:'center',justifyContent:'center'},accountRowTitle:{fontSize:15,fontWeight:'900',color:'#111'},accountRowText:{fontSize:12,color:'#777',marginTop:2},accountDivider:{height:1,backgroundColor:'#eee',marginVertical:10},dangerTitle:{fontSize:14,fontWeight:'900',color:'#a4001e',marginBottom:6},dangerText:{fontSize:12,color:'#777',lineHeight:18,marginBottom:14},deleteButton:{height:50,borderRadius:15,borderWidth:1,borderColor:'#ffccd5',backgroundColor:'#fff5f7',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},deleteButtonText:{fontSize:14,fontWeight:'900',color:'#d70026'},
 onboardingBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,.42)',justifyContent:'flex-end'},onboardingSheet:{backgroundColor:'#fff',borderTopLeftRadius:30,borderTopRightRadius:30,paddingHorizontal:22,paddingTop:10,paddingBottom:24},onboardingHandle:{width:44,height:5,borderRadius:3,backgroundColor:'#d8d8df',alignSelf:'center',marginBottom:18},onboardingIcon:{width:58,height:58,borderRadius:18,backgroundColor:'#6b2cff',alignItems:'center',justifyContent:'center',alignSelf:'center',marginBottom:14},onboardingTitle:{fontSize:23,fontWeight:'900',color:'#111',textAlign:'center',marginBottom:10},onboardingText:{fontSize:15,color:'#666',lineHeight:21,textAlign:'center',marginBottom:8},onboardingButton:{height:54,borderRadius:18,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:12},onboardingButtonText:{color:'#fff',fontSize:16,fontWeight:'900'},onboardingLater:{height:44,alignItems:'center',justifyContent:'center',marginTop:4},onboardingLaterText:{fontSize:14,fontWeight:'800',color:'#777'}
});
